### ISSUE TITLE
401 Client Error: Unauthorized for url: https://api.xero.com/api.xro/2.0/Currencies

### ISSUE THREAD

**Issue by smcleodau** [singer-io/tap-xero#38] opened 2018-03-16 16:45 UTC
HI there - I'm not sure if the endpoints have changed or similar?

[100518-69022-1521216060.zip](https://github.com/singer-io/tap-xero/files/1820066/100518-69022-1521216060.zip)

**Comment by dmosorast** [comment] 2018-03-20 18:45
Hi @smcleodau, I've just been able to complete a sync using the most recent version of the tap. [Xero's docs](https://developer.xero.com/documentation/auth-and-limits/oauth-issues) suggest that this could be caused by a few different situations.

Given that the auth code hasn't changed in the tap recently, I suspect that something may have changed with the user or oauth grant on Xero's end. It might be worth it to re-authorize the connection with Xero to see if that fixes it.

**Comment by dmosorast** [comment] 2018-03-21 17:35
Further testing indicates that this was an issue with refreshing credentials. Should be fixed by #39

**Closed** 2018-03-21 18:53 UTC
